export const demoFreelancers = [
  {
    id: "1",
    name: "Ahmed Ben Ali",
    email: "ahmed.benali@email.com",
    title: "Développeur Full Stack",
    rating: 4.9,
    reviews: 127,
    location: "Tunis",
    price: "25 DT/h",
    skills: ["React", "Node.js", "MongoDB", "TypeScript", "Next.js"],
    avatar: "/placeholder.svg?height=60&width=60",
    description:
      "Développeur expérimenté avec 5 ans d'expérience en développement web moderne. Spécialisé dans React, Node.js et les applications full-stack.",
    availability: "Disponible",
    experience: "5 ans",
    completedProjects: 45,
    responseTime: "2h",
    languages: ["Français", "Arabe", "Anglais"],
    portfolio: [
      { title: "E-commerce Platform", image: "/placeholder.svg?height=200&width=300", tech: ["React", "Node.js"] },
      { title: "Mobile App", image: "/placeholder.svg?height=200&width=300", tech: ["React Native"] },
    ],
  },
  {
    id: "2",
    name: "Fatma Trabelsi",
    email: "fatma.trabelsi@email.com",
    title: "Designer UI/UX",
    rating: 4.8,
    reviews: 89,
    location: "Sfax",
    price: "20 DT/h",
    skills: ["Figma", "Adobe XD", "Photoshop", "Illustrator", "Sketch"],
    avatar: "/placeholder.svg?height=60&width=60",
    description:
      "Designer créative spécialisée dans les interfaces modernes et intuitives. Passionnée par l'expérience utilisateur et le design thinking.",
    availability: "Occupée",
    experience: "4 ans",
    completedProjects: 67,
    responseTime: "4h",
    languages: ["Français", "Arabe"],
    portfolio: [
      { title: "Banking App UI", image: "/placeholder.svg?height=200&width=300", tech: ["Figma", "Prototyping"] },
      { title: "Restaurant Website", image: "/placeholder.svg?height=200&width=300", tech: ["Adobe XD"] },
    ],
  },
  {
    id: "3",
    name: "Mohamed Karray",
    email: "mohamed.karray@email.com",
    title: "Expert Marketing Digital",
    rating: 4.7,
    reviews: 156,
    location: "Sousse",
    price: "30 DT/h",
    skills: ["SEO", "Google Ads", "Social Media", "Analytics", "Content Marketing"],
    avatar: "/placeholder.svg?height=60&width=60",
    description:
      "Spécialiste en marketing digital avec expertise en SEO et publicité en ligne. Aide les entreprises à augmenter leur visibilité.",
    availability: "Disponible",
    experience: "6 ans",
    completedProjects: 89,
    responseTime: "1h",
    languages: ["Français", "Arabe", "Anglais"],
    portfolio: [
      { title: "SEO Campaign", image: "/placeholder.svg?height=200&width=300", tech: ["SEO", "Analytics"] },
      {
        title: "Social Media Strategy",
        image: "/placeholder.svg?height=200&width=300",
        tech: ["Facebook Ads", "Instagram"],
      },
    ],
  },
  {
    id: "4",
    name: "Leila Mansouri",
    email: "leila.mansouri@email.com",
    title: "Développeuse Mobile",
    rating: 4.9,
    reviews: 73,
    location: "Tunis",
    price: "28 DT/h",
    skills: ["Flutter", "React Native", "iOS", "Android", "Firebase"],
    avatar: "/placeholder.svg?height=60&width=60",
    description:
      "Développeuse mobile passionnée, spécialisée dans Flutter et React Native. Créatrice d'applications performantes et intuitives.",
    availability: "Disponible",
    experience: "3 ans",
    completedProjects: 32,
    responseTime: "3h",
    languages: ["Français", "Arabe", "Anglais"],
    portfolio: [
      { title: "Delivery App", image: "/placeholder.svg?height=200&width=300", tech: ["Flutter", "Firebase"] },
      { title: "Fitness Tracker", image: "/placeholder.svg?height=200&width=300", tech: ["React Native"] },
    ],
  },
  {
    id: "5",
    name: "Youssef Gharbi",
    email: "youssef.gharbi@email.com",
    title: "Rédacteur & Traducteur",
    rating: 4.6,
    reviews: 94,
    location: "Monastir",
    price: "15 DT/h",
    skills: ["Rédaction", "Traduction", "SEO Writing", "Copywriting", "Content Strategy"],
    avatar: "/placeholder.svg?height=60&width=60",
    description:
      "Rédacteur professionnel et traducteur trilingue. Spécialisé dans la création de contenu engageant et optimisé SEO.",
    availability: "Disponible",
    experience: "4 ans",
    completedProjects: 156,
    responseTime: "2h",
    languages: ["Français", "Arabe", "Anglais"],
    portfolio: [
      { title: "Blog Articles", image: "/placeholder.svg?height=200&width=300", tech: ["SEO Writing"] },
      { title: "Website Copy", image: "/placeholder.svg?height=200&width=300", tech: ["Copywriting"] },
    ],
  },
  {
    id: "6",
    name: "Sarra Bouaziz",
    email: "sarra.bouaziz@email.com",
    title: "Graphiste & Illustratrice",
    rating: 4.8,
    reviews: 112,
    location: "Gabès",
    price: "22 DT/h",
    skills: ["Illustrator", "Photoshop", "InDesign", "Branding", "Logo Design"],
    avatar: "/placeholder.svg?height=60&width=60",
    description:
      "Graphiste créative avec un œil artistique pour le branding et l'identité visuelle. Transforme vos idées en designs mémorables.",
    availability: "Disponible",
    experience: "5 ans",
    completedProjects: 78,
    responseTime: "4h",
    languages: ["Français", "Arabe"],
    portfolio: [
      { title: "Brand Identity", image: "/placeholder.svg?height=200&width=300", tech: ["Illustrator", "Branding"] },
      { title: "Logo Collection", image: "/placeholder.svg?height=200&width=300", tech: ["Logo Design"] },
    ],
  },
]

export const demoClients = [
  {
    id: "1",
    name: "Mohamed Sassi",
    email: "mohamed.sassi@startup.tn",
    company: "TechStart Tunisia",
    location: "Tunis",
    avatar: "/placeholder.svg?height=60&width=60",
    joinDate: "2023-10-15",
    projectsPosted: 8,
    totalSpent: "12,500 DT",
    rating: 4.7,
    description:
      "Entrepreneur passionné, fondateur de TechStart Tunisia. Toujours à la recherche de talents pour développer des solutions innovantes.",
  },
  {
    id: "2",
    name: "Amina Khelifi",
    email: "amina@restaurant-medina.tn",
    company: "Restaurant Medina",
    location: "Sousse",
    avatar: "/placeholder.svg?height=60&width=60",
    joinDate: "2023-11-20",
    projectsPosted: 3,
    totalSpent: "2,800 DT",
    rating: 4.9,
    description:
      "Propriétaire du Restaurant Medina, cherche à moderniser sa présence digitale et améliorer l'expérience client.",
  },
  {
    id: "3",
    name: "Karim Ben Salah",
    email: "karim@ecommerce-tn.com",
    company: "E-Commerce TN",
    location: "Sfax",
    avatar: "/placeholder.svg?height=60&width=60",
    joinDate: "2023-09-10",
    projectsPosted: 12,
    totalSpent: "18,900 DT",
    rating: 4.8,
    description:
      "Directeur d'une plateforme e-commerce en croissance. Recherche constamment des développeurs et designers talentueux.",
  },
]

export const demoProjects = [
  {
    id: "1",
    title: "Site E-commerce Moderne",
    description:
      "Développement d'une plateforme e-commerce complète avec panier, paiement en ligne, gestion des stocks et tableau de bord administrateur. Interface moderne et responsive.",
    client: demoClients[2],
    freelancer: demoFreelancers[0],
    budget: 1500,
    status: "in_progress" as const,
    progress: 75,
    deadline: "2024-02-15",
    skills_required: ["React", "Node.js", "MongoDB", "Stripe", "Tailwind CSS"],
    created_at: "2024-01-01",
    category: "Développement Web",
    priority: "Haute",
    attachments: [
      { name: "Cahier des charges.pdf", size: "2.3 MB" },
      { name: "Maquettes.fig", size: "15.7 MB" },
    ],
  },
  {
    id: "2",
    title: "Application Mobile de Livraison",
    description:
      "Création d'une application mobile cross-platform pour service de livraison avec géolocalisation, suivi en temps réel, système de notation et paiement intégré.",
    client: demoClients[0],
    freelancer: demoFreelancers[3],
    budget: 3000,
    status: "in_progress" as const,
    progress: 45,
    deadline: "2024-03-01",
    skills_required: ["Flutter", "Firebase", "Google Maps API", "Payment Gateway"],
    created_at: "2024-01-15",
    category: "Développement Mobile",
    priority: "Haute",
    attachments: [
      { name: "Wireframes.pdf", size: "5.1 MB" },
      { name: "API Documentation.pdf", size: "1.8 MB" },
    ],
  },
  {
    id: "3",
    title: "Identité Visuelle Restaurant",
    description:
      "Création complète de l'identité visuelle pour un restaurant traditionnel : logo, carte de visite, menu, signalétique et déclinaisons digitales.",
    client: demoClients[1],
    freelancer: demoFreelancers[5],
    budget: 800,
    status: "completed" as const,
    progress: 100,
    deadline: "2024-01-20",
    skills_required: ["Logo Design", "Branding", "Print Design", "Illustrator"],
    created_at: "2023-12-20",
    category: "Design Graphique",
    priority: "Moyenne",
    attachments: [
      { name: "Brief créatif.pdf", size: "1.2 MB" },
      { name: "Références visuelles.zip", size: "8.4 MB" },
    ],
  },
  {
    id: "4",
    title: "Refonte Site Web Corporate",
    description:
      "Refonte complète du site web d'entreprise avec nouveau design, optimisation SEO, intégration CMS et version mobile. Focus sur l'expérience utilisateur.",
    client: demoClients[0],
    freelancer: demoFreelancers[1],
    budget: 2200,
    status: "published" as const,
    progress: 0,
    deadline: "2024-04-01",
    skills_required: ["UI/UX Design", "WordPress", "SEO", "Responsive Design"],
    created_at: "2024-01-25",
    category: "Design Web",
    priority: "Moyenne",
    attachments: [{ name: "Audit site actuel.pdf", size: "3.7 MB" }],
  },
  {
    id: "5",
    title: "Campagne Marketing Digital",
    description:
      "Stratégie marketing complète incluant SEO, Google Ads, réseaux sociaux et content marketing pour augmenter la visibilité en ligne d'une startup tech.",
    client: demoClients[0],
    freelancer: demoFreelancers[2],
    budget: 1800,
    status: "in_progress" as const,
    progress: 60,
    deadline: "2024-02-28",
    skills_required: ["SEO", "Google Ads", "Social Media", "Content Marketing", "Analytics"],
    created_at: "2024-01-10",
    category: "Marketing Digital",
    priority: "Haute",
    attachments: [
      { name: "Analyse concurrentielle.pdf", size: "4.2 MB" },
      { name: "Stratégie contenu.docx", size: "890 KB" },
    ],
  },
  {
    id: "6",
    title: "Rédaction Contenu Blog Tech",
    description:
      "Rédaction de 20 articles de blog optimisés SEO sur les tendances technologiques, l'innovation et le digital en Tunisie. Ton professionnel et engageant.",
    client: demoClients[0],
    freelancer: demoFreelancers[4],
    budget: 600,
    status: "published" as const,
    progress: 0,
    deadline: "2024-03-15",
    skills_required: ["Rédaction", "SEO Writing", "Recherche", "Content Strategy"],
    created_at: "2024-01-28",
    category: "Rédaction",
    priority: "Basse",
    attachments: [
      { name: "Liste sujets.xlsx", size: "45 KB" },
      { name: "Guidelines rédaction.pdf", size: "1.1 MB" },
    ],
  },
  {
    id: "7",
    title: "Dashboard Analytics Avancé",
    description:
      "Développement d'un tableau de bord analytics avec visualisations interactives, rapports automatisés et intégration APIs multiples pour suivi KPIs business.",
    client: demoClients[2],
    freelancer: null,
    budget: 2800,
    status: "published" as const,
    progress: 0,
    deadline: "2024-04-15",
    skills_required: ["React", "D3.js", "Python", "API Integration", "Data Visualization"],
    created_at: "2024-01-30",
    category: "Développement Web",
    priority: "Haute",
    attachments: [{ name: "Spécifications techniques.pdf", size: "6.3 MB" }],
  },
  {
    id: "8",
    title: "App Mobile Fitness",
    description:
      "Application mobile de fitness avec suivi d'entraînements, programmes personnalisés, intégration wearables et communauté d'utilisateurs.",
    client: demoClients[0],
    freelancer: null,
    budget: 3500,
    status: "published" as const,
    progress: 0,
    deadline: "2024-05-01",
    skills_required: ["React Native", "HealthKit", "Firebase", "Push Notifications"],
    created_at: "2024-02-01",
    category: "Développement Mobile",
    priority: "Moyenne",
    attachments: [
      { name: "User Stories.pdf", size: "2.8 MB" },
      { name: "Mockups.fig", size: "12.4 MB" },
    ],
  },
]

export const demoServices = [
  {
    id: "1",
    freelancer_id: "1",
    freelancer: demoFreelancers[0],
    title: "Développement Site Web React/Next.js",
    description:
      "Création de sites web modernes et performants avec React et Next.js. Interface responsive, optimisation SEO, intégration APIs et déploiement inclus.",
    price_from: 800,
    category: "Développement Web",
    delivery_time: "2-3 semaines",
    revisions: 3,
    features: ["Design responsive", "Optimisation SEO", "Intégration CMS", "Déploiement inclus", "Support 30 jours"],
    portfolio_images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    is_active: true,
    rating: 4.9,
    orders_completed: 23,
  },
  {
    id: "2",
    freelancer_id: "1",
    freelancer: demoFreelancers[0],
    title: "Application Web Full-Stack",
    description:
      "Développement d'applications web complètes avec backend Node.js, base de données, authentification et interface utilisateur moderne.",
    price_from: 1500,
    category: "Développement Web",
    delivery_time: "4-6 semaines",
    revisions: 2,
    features: ["Backend Node.js", "Base de données MongoDB", "Authentification JWT", "API REST", "Tests inclus"],
    portfolio_images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    is_active: true,
    rating: 4.8,
    orders_completed: 15,
  },
  {
    id: "3",
    freelancer_id: "2",
    freelancer: demoFreelancers[1],
    title: "Design UI/UX Complet",
    description:
      "Conception d'interfaces utilisateur modernes et intuitives. Recherche utilisateur, wireframes, prototypes interactifs et guide de style inclus.",
    price_from: 600,
    category: "Design",
    delivery_time: "2-3 semaines",
    revisions: 5,
    features: [
      "Recherche utilisateur",
      "Wireframes détaillés",
      "Prototypes interactifs",
      "Guide de style",
      "Fichiers sources",
    ],
    portfolio_images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    is_active: true,
    rating: 4.9,
    orders_completed: 31,
  },
  {
    id: "4",
    freelancer_id: "3",
    freelancer: demoFreelancers[2],
    title: "Stratégie SEO Complète",
    description:
      "Audit SEO complet, optimisation technique, recherche de mots-clés, création de contenu et suivi des performances pour améliorer votre visibilité.",
    price_from: 500,
    category: "Marketing Digital",
    delivery_time: "3-4 semaines",
    revisions: 2,
    features: [
      "Audit SEO technique",
      "Recherche mots-clés",
      "Optimisation on-page",
      "Stratégie contenu",
      "Rapport mensuel",
    ],
    portfolio_images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    is_active: true,
    rating: 4.7,
    orders_completed: 42,
  },
  {
    id: "5",
    freelancer_id: "4",
    freelancer: demoFreelancers[3],
    title: "Application Mobile Flutter",
    description:
      "Développement d'applications mobiles cross-platform avec Flutter. Interface native, performances optimales et publication sur les stores incluse.",
    price_from: 1200,
    category: "Développement Mobile",
    delivery_time: "4-5 semaines",
    revisions: 3,
    features: ["Cross-platform", "Interface native", "Intégration APIs", "Publication stores", "Support technique"],
    portfolio_images: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    is_active: true,
    rating: 4.8,
    orders_completed: 18,
  },
]

export const demoReviews = [
  {
    id: "1",
    project_id: "3",
    reviewer_id: "2",
    reviewer_name: "Amina Khelifi",
    reviewed_id: "6",
    reviewed_name: "Sarra Bouaziz",
    rating: 5,
    comment:
      "Travail exceptionnel ! Sarra a parfaitement compris notre vision et a créé une identité visuelle qui reflète l'âme de notre restaurant. Communication excellente et délais respectés.",
    created_at: "2024-01-22",
  },
  {
    id: "2",
    project_id: "1",
    reviewer_id: "3",
    reviewer_name: "Karim Ben Salah",
    reviewed_id: "1",
    reviewed_name: "Ahmed Ben Ali",
    rating: 5,
    comment:
      "Ahmed est un développeur de très haut niveau. Le site e-commerce dépasse nos attentes en termes de fonctionnalités et de performance. Je recommande vivement !",
    created_at: "2024-01-20",
  },
  {
    id: "3",
    project_id: "5",
    reviewer_id: "1",
    reviewer_name: "Mohamed Sassi",
    reviewed_id: "3",
    reviewed_name: "Mohamed Karray",
    rating: 4,
    comment:
      "Très bon travail sur notre stratégie marketing. Les résultats commencent déjà à se voir. Mohamed est professionnel et à l'écoute.",
    created_at: "2024-01-18",
  },
]

export const demoStats = {
  totalUsers: 7234,
  totalFreelancers: 2156,
  totalClients: 1890,
  totalProjects: 1456,
  completedProjects: 1123,
  activeProjects: 333,
  totalRevenue: 456700,
  monthlyRevenue: 45670,
  averageProjectValue: 1850,
  successRate: 94.2,
}
